# Generated by Django 2.1.2 on 2018-11-14 19:55

import betlog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanceAdjust', betlog.models.MyMoneyField(decimal_places=2, default=5.0, max_digits=7, verbose_name='Balance Adjust')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=20, verbose_name='Team 1')),
                ('team2', models.CharField(max_length=20, verbose_name='Team 2')),
                ('inPlay', models.BooleanField(default=True, editable=False, verbose_name='In-play')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Complete')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid character or space', regex='[a-zA-Z0-9 ]+')], verbose_name='Name')),
                ('balance', betlog.models.MyMoneyField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Balance')),
                ('openBets', models.IntegerField(default=0, editable=False, verbose_name='Open Bets')),
                ('comment', models.CharField(blank=True, default='None', max_length=255, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanceAdjust', betlog.models.MyMoneyField(decimal_places=2, default=10.0, max_digits=7, verbose_name='Balance Adjust pls')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betlog.Site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betlog.TransactionType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bet',
            name='betType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betlog.BetType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betlog.Match', verbose_name='Match'),
        ),
        migrations.AddField(
            model_name='bet',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betlog.Site', verbose_name='Site'),
        ),
    ]
