# Generated by Django 2.1.2 on 2018-10-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
