# Generated by Django 2.1.2 on 2018-11-02 16:33

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('betlog', '0003_auto_20181102_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='balance',
            field=djmoney.models.fields.MoneyField(currency_choices=[('GBP', 'GBP £')], decimal_places=2, default=Decimal('0'), default_currency='GBP', editable=False, max_digits=14, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='site',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3),
        ),
    ]
