# Generated by Django 2.1.2 on 2018-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betlog', '0004_auto_20181121_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Comments'),
        ),
    ]
