# Generated by Django 2.1.2 on 2018-11-02 18:05

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('betlog', '0004_auto_20181102_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balanceAdjust_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balanceAdjust',
            field=djmoney.models.fields.MoneyField(currency_choices=[('GBP', 'GBP £')], decimal_places=2, default=Decimal('10.0'), default_currency='GBP', max_digits=7, verbose_name='Balance Adjust'),
        ),
    ]
