# Generated by Django 2.1.2 on 2018-11-22 19:48

import betlog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betlog', '0005_auto_20181121_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balanceAdjust',
            field=betlog.models.MyMoneyField(decimal_places=2, default=10.0, max_digits=7, verbose_name='Balance Adjust'),
        ),
    ]
