# Generated by Django 2.1.2 on 2018-11-02 21:34

import betlog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betlog', '0006_auto_20181102_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='balanceAdjust',
            field=betlog.models.MyMoneyField(decimal_places=2, default=5.0, max_digits=7, verbose_name='Balance Adjust'),
        ),
    ]
